version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "monthly"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      Microsoft:
        patterns:
          - "Microsoft.*"
      FluentEmail:
        patterns:
          - "jcamp.FluentEmail.*"
      OpenTelemetry:
        patterns:
          - "OpenTelemetry.*"
      xunit:
        patterns:
          - "xunit.*"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
