version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "monthly"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      Microsoft:
        patterns:
          - "Microsoft.*"
      FluentEmail:
        patterns:
          - "jcamp.FluentEmail.*"
      OpenTelemetry:
        patterns:
          - "OpenTelemetry.*"